config/routes.rb
Rails.application.routes.draw do
  resources :orders

  get 'welcome/index'

  root 'welcome#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :email, :model, :details)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cloudmotors</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for @order, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= error_span(@order[:name]) %>
  <%= f.input :email %>
  <%= error_span(@order[:email]) %>
  <%= f.input :model %>
  <%= error_span(@order[:model]) %>
  <%= f.input :details %>
  <%= error_span(@order[:details]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                orders_path, :class => 'btn btn-default' %>
<% end %>

app/views/orders/edit.html.erb
<%- model_class = Order -%>
<div class="container">
	<div class="page-header">
	  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/orders/index.html.erb
<%- model_class = Order -%>
<div class="container">
	
	<div class="page-header">
	  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
	</div>
	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th><%= model_class.human_attribute_name(:id) %></th>
	      <th><%= model_class.human_attribute_name(:name) %></th>
	      <th><%= model_class.human_attribute_name(:email) %></th>
	      <th><%= model_class.human_attribute_name(:model) %></th>
	      <th><%= model_class.human_attribute_name(:details) %></th>
	      <th><%= model_class.human_attribute_name(:created_at) %></th>
	      <th><%=t '.actions', :default => t("helpers.actions") %></th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @orders.each do |order| %>
	      <tr>
	        <td><%= link_to order.id, order_path(order) %></td>
	        <td><%= order.name %></td>
	        <td><%= order.email %></td>
	        <td><%= order.model %></td>
	        <td><%= order.details %></td>
	        <td><%=l order.created_at %></td>
	        <td>
	          <%= link_to t('.edit', :default => t("helpers.links.edit")),
	                      edit_order_path(order), :class => 'btn btn-default btn-xs' %>
	          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                      order_path(order),
	                      :method => :delete,
	                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                      :class => 'btn btn-xs btn-danger' %>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
	<%= link_to t('.new', :default => t("helpers.links.new")),
	            new_order_path,
	            :class => 'btn btn-primary' %>
</div>

app/views/orders/new.html.erb
<%- model_class = Order -%>
<div class="container">
	<div class="page-header">
	  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
	</div>
	<%= render :partial => 'form' %>
</div>

app/views/orders/show.html.erb
<%- model_class = Order -%>
<div class="container">
	<div class="page-header">
	  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
	</div>
	
	<dl class="dl-horizontal">
	  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
	  <dd><%= @order.name %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
	  <dd><%= @order.email %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
	  <dd><%= @order.model %></dd>
	  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
	  <dd><%= @order.details %></dd>
	</dl>
	
	<%= link_to t('.back', :default => t("helpers.links.back")),
	              orders_path, :class => 'btn btn-default'  %>
	<%= link_to t('.edit', :default => t("helpers.links.edit")),
	              edit_order_path(@order), :class => 'btn btn-default' %>
	<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	              order_path(@order),
	              :method => 'delete',
	              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	              :class => 'btn btn-danger' %>
</div>

app/views/welcome/index.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Cloud Motors</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="/orders/">Orders</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
		
        <!-- Jumbotron Header -->
        <header class="jumbotron hero-spacer">        	
            <h1><%= link_to image_tag("CloudMotorsLogo.png", alt: "Cloud Motors"), '/' %> April's Deals! </h1>    
            <h2></h2>        
            <p>Thinking on the emergent market Cloud Motors is gattering people willing to get a brand new smashed car. Check out the models and make your choice! </p>
        </header>

        <hr>

        <!-- Title -->
        <div class="row">
            <div class="col-lg-12">
                <h3>Available Models</h3>
            </div>
        </div>
        <!-- /.row -->

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= link_to image_tag("derby3.jpg", alt: "Car"), '/' %>
                    <div class="caption">
                        <h3>Camo Suburban</h3>
                        <p>With a single seat, no seatbelts and no windshields. Feel the breeze!</p>
                        <p>
                            <a href="/orders/new" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= link_to image_tag("derby11.jpg", alt: "Car"), '/' %>
                    <div class="caption">
                        <h3>Daredevil</h3>
                        <p>Classic saloon with rear seat, take your children to a tour with you.</p>
                        <p>
                            <a href="/orders/new" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= link_to image_tag("derby16.jpg", alt: "Car"), '/' %>
                    <div class="caption">
                        <h3>Mindblower</h3>
                        <p>With a V8 engine this powerful car can blow more than your head.</p>
                        <p>
                            <a href="/orders/new" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-md-3 col-sm-6 hero-feature">
                <div class="thumbnail">
                    <%= link_to image_tag("derby20.jpg", alt: "Car"), '/' %>
                    <div class="caption">
                        <h3>Outlander</h3>
                        <p>Like you can be sexy yet not banal have this off-road with a city charm.</p>
                        <p>
                            <a href="/orders/new" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->

        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Cloud Motors 2015</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->